### ISSUE TITLE
Elaborar workshop sobre SQL

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-etl#39]
O objetivo aqui é ajudar todos da equipe do INDI a entender melhor como os dados são trabalhados usando scripts SQL, por exemplo: 
- [create_SC_2015_DOCENTE.sql](https://github.com/DataViva/dataviva-etl/blob/master/censo_escolar/ddl/create_SC_2015_MATRICULA.sql)

- [select_SC_2015_MATRICULA.sql](https://github.com/DataViva/dataviva-etl/blob/master/censo_escolar/select/select_SC_2015_MATRICULA.sql)

**Comment by leandrocollares** [comment]
Workshop iniciado em 18/04.

**Comment by litodaldegan** [comment]
Treinamento encerrado até que seja identificado a necessidade de continuidade.
