### ISSUE TITLE
Censo Escolar - Melhorar descrição dos comentários

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-etl#42]
Para começarmos a ter uma documentação mais rica, precisamos melhorar os comentários feitos para cada um dos passos durante a transformação. Exemplo:
- [select_SC_2015_MATRICULA.sql](https://github.com/DataViva/dataviva-etl/blob/master/censo_escolar/select/select_SC_2015_MATRICULA.sql)

**Comment by litodaldegan** [comment]
Cometários adicionados aos _scripts_ de transformação e carregamento dos dados. Também foram realizadas melhorias na documentação de forma que fique alinhada com as alterações realizadas nos _script_.

Commit: bc9d25d8c44f2908f70e63e686b19c5ed46d2dea
