### ISSUE TITLE
Censo Escolar - Apontar os dados retirados na documentação

### ISSUE THREAD

**Issue by diogolundberg** [DataViva/dataviva-etl#43]
Precisamos identificar melhor os dados que foram filtrados e ficaram de fora da base de dados.
- [select_SC_2015_MATRICULA.sql#L98](https://github.com/DataViva/dataviva-etl/blob/master/censo_escolar/select/select_SC_2015_MATRICULA.sql#L98)

**Comment by litodaldegan** [comment]
Os dados removidos/filtrados foram identificados no script de transformação (bc9d25d) e também foram citados na documentação ETL.
