### ISSUE TITLE
Verificar a necessidade de atualização dos metadados da RAIS

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-etl#54]
Deve ser verificado no dicionários de dados de cada uma das bases RAIS a serem atualizadas (2015,2016) se há necessidade de atualização dos metadados relacionados.

**Comment by msbandrade** [comment]
Os metadados foram verificados e foi atualizado o metadados referente à CBO. Demais variáveis já estão em sua última versão.
