### ISSUE TITLE
Criar script que faz as transformações dos dados da RAIS 2015

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-etl#58]
Validar as transformações em uma amostra dos dados para não gastar muito tempo aguardando o processamento.

DOD:
- Script de transformação no repositório dataviva_etl
- Dados transformados no dataviva_etl

**Comment by leandrocollares** [comment]
- Script criado e utilizado **localmente** para transformar dados do Acre e de Minas Gerais. 
- Validação dos dados transformados dos dois estados mencionados realizada com sucesso. 
- Script para transformação dos dados de todos os estados em execução.

**Comment by leandrocollares** [comment]
Script criado e adicionado ao repositório dataviva-etl.

**Comment by leandrocollares** [comment]
Dados transformados em dataviva-etl.
