### ISSUE TITLE
Disponibilizar dados da RAIS 2016 no ambiente de staging

### ISSUE THREAD

**Issue by litodaldegan** [DataViva/dataviva-etl#67]
Estando os dados da RAIS 2016 validados (tarefa #66), os mesmos devem ser colocados no ambiente de staging para uma última validação visual deles sendo exibidos nas visualizações.

Ao terminar, importante verificar se a quantidade de dados carregados correspondem ao total encontrado no processo de ETL e desligar a máquina de ETL.

**Comment by leandrocollares** [comment]
Dados disponibilizados em _staging_.
