### ISSUE TITLE
Tabela indicadores RAIS 2015

### ISSUE THREAD

**Issue by msbandrade** [DataViva/dataviva-etl#82]
Subir para o MySQL/staging a tabela com os indicadores da RAIS 2015 (espaço de atividades). A tabela já está disponível no S3: https://s3.console.aws.amazon.com/s3/buckets/tabelas-indicadores/rais/2015/?region=us-east-1&tab=overview

@litodaldegan @josianefaleiro

**Comment by litodaldegan** [comment]
@msbandrade e @josianefaleiro 
Dados em ambiente de staging, favor validar. Se estiver tudo certo, colocamos em produção.
